name: PyPI Release

on: [ release ]

jobs:
  test:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Get tag version from tag
      run: |
        version=${GITHUB_REF/refs\/tags\/v}
        echo ::set-output name=VERSION::$version
        sed -i "s/version = '.*'/version = '$version'/" setup.py
    - name: Commit new version
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Release version ${{ env.VERSION }}
    - name: Build release
      run: |
        python setup.py sdist bdist_wheel
    - name: Publish release
      uses: pypa/gh-action-pypi-publish@v1.3.1
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
