name: PyPI

on:
  release:
    types: [ published ]

jobs:
  release:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools wheel
    - name: Get tag version from tag
      run: |
        version=${GITHUB_REF/refs\/tags\/v}
        echo "VERSION=$version" >> $GITHUB_ENV
        sed -i "s/version = '.*'/version = '$version'/" setup.py
    - name: Commit new version
      uses: stefanzweifel/git-auto-commit-action@v4.11.0
      with:
        commit_message: 🚢 Upload v${{ env.VERSION }} to PyPI
    - name: Build release
      run: |
        python setup.py sdist bdist_wheel
    - name: Publish release
      uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
