name: Tests

on: [ push ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-20.04
        - macos-10.15
        - windows-2019
        python-version:
        - 3.8

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python setup.py develop
        pip install -r requirements-dev.txt
    - name: Typecheck with mypy
      run: |
        mypy .
    - name: Test with pytest
      run: |
        pytest --cov=govyn --cov-report=xml
    - name: Upload code coverage
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        fail_ci_if_error: false # temp fix for timeouts
