name: Tests

on: [ push ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-20.04
        - macos-10.15
        - windows-2019
        python-version:
        - 3.8
        - 3.9
        python-deps-level:
        - min
        - pypi

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install --upgrade pip wheel
        pip install -r requirements-dev.txt
        requirements-builder -l ${{ matrix.python-deps-level }} setup.py > generated-requirements.txt
        pip install -r generated-requirements.txt
    - name: Typecheck with mypy
      run: |
        mypy .
    - name: Test with pytest
      run: |
        pytest --cov=govyn --cov-report=xml
